### ISSUE TITLE
Ember-Data 1.0.0-beta.15 not working with Ember-Pouch?

### ISSUE THREAD

**Issue by broerse** [nolanlawson/ember-pouch#45]
I don't know for sure if this is a ember-pouch thing but it seems ember-data gives an error on destroyRecord(). 

json_serializer.js:544 Uncaught TypeError: undefined is not a function

In the serializeAttribute: sub on: snapshot.attr 

If I go back to 1.0.0-beta.14.1 all works again

Is there somebody who can confirm Ember-Pouch and destroyRecord() works with Ember-Data 1.0.0-beta.15 ?

I will investigate further.

**Comment by rsutphin** [comment]
@broerse, I'm seeing the same exception when I upgrade my app to beta.15. I'm staying on beta-14.1 for now due to an upcoming deadline, but will take a look in a couple of weeks (if no one else beats me to it).

**Comment by OleRoel** [comment]
This might be helpful:

https://github.com/emberjs/data/issues/2801

I find the comment by https://github.com/wecc interesting:

> @esbanarango are you using ember-sync or any custom adapter/serializer? I would suspect that there's a code path somewhere that passes the model itself instead of a snapshot to the serializer.

**Comment by broerse** [comment]
@rsutphin @OleRoel @nolanlawson This fixed it for the other framework:

https://github.com/kurko/ember-sync/commit/ca2e824052626bc3ef9c9b015961878fd4fd1be7

Something in Ember Pouch is passing a record instead of a snapshot?

**Comment by OleRoel** [comment]
@broerse @rsutphin @nolanlawson 

Things seems to work after changing [_recordToData](https://github.com/nolanlawson/ember-pouch/blob/master/dist/globals/main.js#L123) using the code mentioned by @broerse  above:

```javascript
  _recordToData: function (store, type, record) {
    var data = {};
    var serializer = store.serializerFor(type.typeKey);
    var snapshot = record._createSnapshot();

    serializer.serializeIntoHash(data, type, snapshot, { includeId: true });

    data = data[type.typeKey];

    // ember sets it to null automatically. don't need it.
    if (data.rev === null) {
      delete data.rev;
    }

    return data;
  },
```

The only change is to create a snapshot and pass it into serializeIntoHash instead of the record.

**Comment by nolanlawson** [comment]
I haven't tested out the new Ember Data, but this seems reasonable. If it's not backwards-incompatible, could someone submit a PR? :D

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/ember-pouch/pull/47

**Comment by broerse** [comment]
:sunny:

**Comment by nolanlawson** [comment]
fixed by fdb1d042f61d577ffe8a10d32fd815367c2716df
